name: Sample App Tests

on: push

jobs:
  sample_app_tests:
    name: "Run Tests Using Jest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: scripts/sample-app  # ðŸ‘ˆ CORRIGÃ‰ ICI
        run: npm install

      - name: Run tests
        working-directory: scripts/sample-app  # ðŸ‘ˆ ET ICI
        run: npm test
